"""Initial schema

Revision ID: 6880ae0ac56d
Revises: 
Create Date: 2025-12-04 14:20:43.684178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6880ae0ac56d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('external_id', sa.String(length=500), nullable=True),
    sa.Column('ai_generated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('child_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('garden_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('planting_date', sa.Date(), nullable=True),
    sa.Column('harvest_date', sa.Date(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('watering_frequency_days', sa.Integer(), nullable=False),
    sa.Column('last_watered', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('ai_suggestions', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('produits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(), nullable=True),
    sa.Column('quantité', sa.Float(), nullable=True),
    sa.Column('unité', sa.String(), nullable=True),
    sa.Column('dlc', sa.Date(), nullable=True),
    sa.Column('emplacement', sa.String(), nullable=True),
    sa.Column('catégorie', sa.String(), nullable=True),
    sa.Column('sous_catégorie', sa.String(), nullable=True),
    sa.Column('niveau', sa.Integer(), nullable=True),
    sa.Column('renouvelable', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_produits_id'), 'produits', ['id'], unique=False)
    op.create_index(op.f('ix_produits_nom'), 'produits', ['nom'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('priority', sa.Enum('BASSE', 'MOYENNE', 'HAUTE', name='prioriteenum', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('A_FAIRE', 'EN_COURS', 'TERMINE', 'ANNULE', name='statutenum', native_enum=False), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('ai_priority_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recettes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=200), nullable=True),
    sa.Column('temps_preparation', sa.Integer(), nullable=True),
    sa.Column('temps_cuisson', sa.Integer(), nullable=True),
    sa.Column('difficulté', sa.String(length=50), nullable=True),
    sa.Column('saisonnalité', sa.String(length=20), nullable=True),
    sa.Column('type_repas', sa.String(length=50), nullable=True),
    sa.Column('catégorie', sa.String(length=100), nullable=True),
    sa.Column('portions_adultes', sa.Integer(), nullable=True),
    sa.Column('portions_bébé', sa.Integer(), nullable=True),
    sa.Column('tag_rapide', sa.Boolean(), nullable=True),
    sa.Column('tag_équilibré', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recettes_id'), 'recettes', ['id'], unique=False)
    op.create_index(op.f('ix_recettes_nom'), 'recettes', ['nom'], unique=False)
    op.create_table('recipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('prep_time', sa.Integer(), nullable=True),
    sa.Column('cook_time', sa.Integer(), nullable=True),
    sa.Column('servings', sa.Integer(), nullable=False),
    sa.Column('difficulty', sa.String(length=50), nullable=True),
    sa.Column('ai_generated', sa.Boolean(), nullable=False),
    sa.Column('ai_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('version_type', sa.Enum('CLASSIQUE', 'BATCH_COOKING', 'BEBE', name='versionrecetteenum'), nullable=True),
    sa.Column('baby_instructions', sa.Text(), nullable=True),
    sa.Column('batch_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('weather_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('condition', sa.String(length=100), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('humidity', sa.Integer(), nullable=True),
    sa.Column('wind_speed', sa.Float(), nullable=True),
    sa.Column('precipitation', sa.Float(), nullable=True),
    sa.Column('forecast_data', sa.JSON(), nullable=True),
    sa.Column('ai_tasks_suggested', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date')
    )
    op.create_table('ai_interactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=200), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('response', sa.Text(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('execution_time', sa.Float(), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alertes_stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produit_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('date_alerte', sa.DateTime(), nullable=True),
    sa.Column('résolue', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['produit_id'], ['produits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alertes_stock_id'), 'alertes_stock', ['id'], unique=False)
    op.create_table('batch_meals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('portions', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('A_FAIRE', 'EN_COURS', 'TERMINE', 'ANNULE', name='statutenum', native_enum=False), nullable=False),
    sa.Column('ai_planned', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('parallel_steps', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('total_time_optimized', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('garden_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('weather_condition', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['garden_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingrédients_recette',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recette_id', sa.Integer(), nullable=True),
    sa.Column('nom', sa.String(length=200), nullable=True),
    sa.Column('quantité', sa.Float(), nullable=True),
    sa.Column('unité', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['recette_id'], ['recettes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingrédients_recette_id'), 'ingrédients_recette', ['id'], unique=False)
    op.create_table('inventory_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('min_quantity', sa.Float(), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.Column('ai_alert_sent', sa.Boolean(), nullable=False),
    sa.Column('recipes_used_in', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('module', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('priority', sa.Enum('BASSE', 'MOYENNE', 'HAUTE', name='prioriteenum', native_enum=False), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('produits_recettes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produit_id', sa.Integer(), nullable=True),
    sa.Column('recette_id', sa.Integer(), nullable=True),
    sa.Column('quantité_utilisée', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['produit_id'], ['produits.id'], ),
    sa.ForeignKeyConstraint(['recette_id'], ['recettes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_produits_recettes_id'), 'produits_recettes', ['id'], unique=False)
    op.create_table('project_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('task_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('A_FAIRE', 'EN_COURS', 'TERMINE', 'ANNULE', name='statutenum', native_enum=False), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('estimated_duration', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipe_ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('optional', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('routines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('frequency', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('ai_suggested', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['child_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shopping_lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('needed_quantity', sa.Float(), nullable=False),
    sa.Column('priority', sa.Enum('BASSE', 'MOYENNE', 'HAUTE', name='prioriteenum', native_enum=False), nullable=False),
    sa.Column('purchased', sa.Boolean(), nullable=False),
    sa.Column('ai_suggested', sa.Boolean(), nullable=False),
    sa.Column('store_section', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('purchased_at', sa.DateTime(), nullable=True),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('profile_name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('preferences', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('versions_recette',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recette_base_id', sa.Integer(), nullable=True),
    sa.Column('type_version', sa.String(length=20), nullable=False),
    sa.Column('nom', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('étapes_spécifiques', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ingrédients_modifiés', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('temps_total', sa.Integer(), nullable=True),
    sa.CheckConstraint("type_version IN ('classique', 'batch_cooking', 'bébé')", name='check_version_type'),
    sa.ForeignKeyConstraint(['recette_base_id'], ['recettes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_versions_recette_id'), 'versions_recette', ['id'], unique=False)
    op.create_table('wellbeing_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('mood', sa.Enum('BIEN', 'MOYEN', 'MAL', name='humeurenum', native_enum=False), nullable=False),
    sa.Column('sleep_hours', sa.Float(), nullable=True),
    sa.Column('activity', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('ai_analysis', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['child_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('étapes_recette',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recette_id', sa.Integer(), nullable=True),
    sa.Column('ordre', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['recette_id'], ['recettes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_étapes_recette_id'), 'étapes_recette', ['id'], unique=False)
    op.create_table('routine_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('routine_id', sa.Integer(), nullable=False),
    sa.Column('task_name', sa.String(length=200), nullable=False),
    sa.Column('scheduled_time', sa.String(length=10), nullable=True),
    sa.Column('status', sa.Enum('A_FAIRE', 'EN_COURS', 'TERMINE', 'ANNULE', name='statutenum', native_enum=False), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('ai_reminder_sent', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['routine_id'], ['routines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('routine_tasks')
    op.drop_index(op.f('ix_étapes_recette_id'), table_name='étapes_recette')
    op.drop_table('étapes_recette')
    op.drop_table('wellbeing_entries')
    op.drop_index(op.f('ix_versions_recette_id'), table_name='versions_recette')
    op.drop_table('versions_recette')
    op.drop_table('user_profiles')
    op.drop_table('shopping_lists')
    op.drop_table('routines')
    op.drop_table('recipe_ingredients')
    op.drop_table('project_tasks')
    op.drop_index(op.f('ix_produits_recettes_id'), table_name='produits_recettes')
    op.drop_table('produits_recettes')
    op.drop_table('notifications')
    op.drop_table('inventory_items')
    op.drop_index(op.f('ix_ingrédients_recette_id'), table_name='ingrédients_recette')
    op.drop_table('ingrédients_recette')
    op.drop_table('garden_logs')
    op.drop_table('batch_meals')
    op.drop_index(op.f('ix_alertes_stock_id'), table_name='alertes_stock')
    op.drop_table('alertes_stock')
    op.drop_table('ai_interactions')
    op.drop_table('weather_logs')
    op.drop_table('users')
    op.drop_table('recipes')
    op.drop_index(op.f('ix_recettes_nom'), table_name='recettes')
    op.drop_index(op.f('ix_recettes_id'), table_name='recettes')
    op.drop_table('recettes')
    op.drop_table('projects')
    op.drop_index(op.f('ix_produits_nom'), table_name='produits')
    op.drop_index(op.f('ix_produits_id'), table_name='produits')
    op.drop_table('produits')
    op.drop_table('ingredients')
    op.drop_table('garden_items')
    op.drop_table('child_profiles')
    op.drop_table('calendar_events')
    # ### end Alembic commands ###
