"""Services du module Habitat."""

from .deco_service import DecoHabitatService, obtenir_service_deco_habitat
from .plans_ai_service import PlansHabitatAIService, obtenir_service_plans_habitat
from .scenarios_service import ScenariosHabitatService, obtenir_service_scenarios_habitat
from .veille_service import VeilleHabitatService, obtenir_service_veille_habitat

get_habitat_scenarios_service = obtenir_service_scenarios_habitat
get_habitat_veille_service = obtenir_service_veille_habitat
get_habitat_plans_service = obtenir_service_plans_habitat
get_habitat_deco_service = obtenir_service_deco_habitat
