-- ============================================================================
-- ASSISTANT MATANNE — Migrations absorbées (V001-V007)
-- ============================================================================
-- Ce fichier documente les migrations qui ont été absorbées dans les fichiers
-- schema/ principaux. Il ne contient plus de SQL exécutable.
--
-- Historique des absorptions :
--   V001 : Index manquants         → absorbé dans 14_indexes.sql
--   V002 : Trigger modifie_le      → absorbé dans 12_triggers.sql
--   V003 : canaux_par_categorie    → absorbé dans 09_notifications.sql
--   V004 : logs_securite + RLS     → absorbé dans 03_systeme.sql + 15_rls_policies.sql
--   V005 : Consolidation SQL       → absorbé dans 14_indexes.sql (CHECK, comments, cleanup)
--   V006 : job_executions          → absorbé dans 03_systeme.sql
--   V007 : Module habitat          → absorbé dans 07_habitat.sql
--   V008 : minuteur_sessions       → absorbé dans 11_utilitaires.sql
--
-- Les fichiers originaux sont conservés dans sql/migrations/ pour référence.
-- ============================================================================
