"""
Constantes pour le package courses.

Mappings rayons et priorités pour la catégorisation des articles.
"""

# Mapping ingrédients -> rayons magasin (complet)
MAPPING_RAYONS: dict[str, str] = {
    # Fruits & Légumes
    "tomate": "Fruits & Légumes",
    "carotte": "Fruits & Légumes",
    "oignon": "Fruits & Légumes",
    "ail": "Fruits & Légumes",
    "pomme de terre": "Fruits & Légumes",
    "courgette": "Fruits & Légumes",
    "poivron": "Fruits & Légumes",
    "salade": "Fruits & Légumes",
    "concombre": "Fruits & Légumes",
    "aubergine": "Fruits & Légumes",
    "champignon": "Fruits & Légumes",
    "poireau": "Fruits & Légumes",
    "chou": "Fruits & Légumes",
    "épinard": "Fruits & Légumes",
    "haricot vert": "Fruits & Légumes",
    "brocoli": "Fruits & Légumes",
    "navet": "Fruits & Légumes",
    "radis": "Fruits & Légumes",
    "fenouil": "Fruits & Légumes",
    "céleri": "Fruits & Légumes",
    "endive": "Fruits & Légumes",
    "betterave": "Fruits & Légumes",
    "artichaut": "Fruits & Légumes",
    "courge": "Fruits & Légumes",
    "potiron": "Fruits & Légumes",
    "butternut": "Fruits & Légumes",
    "patate douce": "Fruits & Légumes",
    "pomme": "Fruits & Légumes",
    "banane": "Fruits & Légumes",
    "orange": "Fruits & Légumes",
    "citron": "Fruits & Légumes",
    "fraise": "Fruits & Légumes",
    "avocat": "Fruits & Légumes",
    "mangue": "Fruits & Légumes",
    "abricot": "Fruits & Légumes",
    "pêche": "Fruits & Légumes",
    "poire": "Fruits & Légumes",
    "raisin": "Fruits & Légumes",
    "kiwi": "Fruits & Légumes",
    "ananas": "Fruits & Légumes",
    "melon": "Fruits & Légumes",
    "cerise": "Fruits & Légumes",
    "fruit": "Fruits & Légumes",
    "légume": "Fruits & Légumes",
    # Herbes fraîches
    "persil": "Fruits & Légumes",
    "coriandre": "Fruits & Légumes",
    "basilic": "Fruits & Légumes",
    "menthe": "Fruits & Légumes",
    "herbe": "Fruits & Légumes",
    "ciboulette": "Fruits & Légumes",
    "thym": "Fruits & Légumes",
    "romarin": "Fruits & Légumes",
    "laurier": "Fruits & Légumes",
    # Boulangerie
    "pain": "Boulangerie",
    "baguette": "Boulangerie",
    "brioche": "Boulangerie",
    # Boucherie
    "poulet": "Boucherie",
    "boeuf": "Boucherie",
    "porc": "Boucherie",
    "veau": "Boucherie",
    "agneau": "Boucherie",
    "steak": "Boucherie",
    "escalope": "Boucherie",
    "dinde": "Boucherie",
    "hach": "Boucherie",
    "viande": "Boucherie",
    # Charcuterie
    "jambon": "Charcuterie",
    "lardon": "Charcuterie",
    "saucisse": "Charcuterie",
    "saucisson": "Charcuterie",
    "merguez": "Charcuterie",
    "chorizo": "Charcuterie",
    "bacon": "Charcuterie",
    # Poissonnerie
    "saumon": "Poissonnerie",
    "cabillaud": "Poissonnerie",
    "crevette": "Poissonnerie",
    "thon": "Poissonnerie",
    "moule": "Poissonnerie",
    "poisson": "Poissonnerie",
    "colin": "Poissonnerie",
    "truite": "Poissonnerie",
    "lieu": "Poissonnerie",
    "sardine": "Poissonnerie",
    # Crèmerie / Frais
    "lait": "Crèmerie",
    "beurre": "Crèmerie",
    "crème": "Crèmerie",
    "yaourt": "Crèmerie",
    "oeuf": "Crèmerie",
    "œuf": "Crèmerie",
    "compote": "Crèmerie",
    "petit-suisse": "Crèmerie",
    # Fromage
    "fromage": "Fromage",
    "gruyère": "Fromage",
    "emmental": "Fromage",
    "parmesan": "Fromage",
    "mozzarella": "Fromage",
    "comté": "Fromage",
    "chèvre": "Fromage",
    "camembert": "Fromage",
    "roquefort": "Fromage",
    "râpé": "Fromage",
    # Épicerie salée
    "pâtes": "Épicerie",
    "riz": "Épicerie",
    "semoule": "Épicerie",
    "quinoa": "Épicerie",
    "boulgour": "Épicerie",
    "couscous": "Épicerie",
    "nouille": "Épicerie",
    "huile": "Épicerie",
    "sel": "Épicerie",
    "poivre": "Épicerie",
    "farine": "Épicerie",
    "sucre": "Épicerie",
    "levure": "Épicerie",
    "maïzena": "Épicerie",
    "bouillon": "Épicerie",
    "épice": "Épicerie",
    "cumin": "Épicerie",
    "paprika": "Épicerie",
    "curry": "Épicerie",
    "curcuma": "Épicerie",
    "cannelle": "Épicerie",
    "gingembre": "Épicerie",
    "noix de muscade": "Épicerie",
    "piment": "Épicerie",
    "origan": "Épicerie",
    "chapelure": "Épicerie",
    # Condiments
    "vinaigre": "Épicerie",
    "moutarde": "Épicerie",
    "sauce soja": "Épicerie",
    "ketchup": "Épicerie",
    "mayonnaise": "Épicerie",
    "sauce": "Épicerie",
    "pesto": "Épicerie",
    "concentré": "Épicerie",
    "coulis": "Épicerie",
    # Conserves
    "conserve": "Épicerie",
    "tomate pelée": "Épicerie",
    "haricot": "Épicerie",
    "pois chiche": "Épicerie",
    "lentille": "Épicerie",
    "maïs": "Épicerie",
    "olive": "Épicerie",
    "câpre": "Épicerie",
    "cornichon": "Épicerie",
    "pulpe": "Épicerie",
    # Petits-déjeuner
    "céréale": "Épicerie",
    "confiture": "Épicerie",
    "miel": "Épicerie",
    "chocolat": "Épicerie",
    "cacao": "Épicerie",
    "nutella": "Épicerie",
    # Boissons
    "jus": "Boissons",
    "eau": "Boissons",
    "sirop": "Boissons",
    # Bio / Végétal
    "tofu": "Bio",
    "lait d'avoine": "Bio",
    "lait de soja": "Bio",
    "tempeh": "Bio",
    # Surgelés
    "surgelé": "Surgelés",
    "glace": "Surgelés",
    # Noix et graines
    "amande": "Épicerie",
    "noisette": "Épicerie",
    "noix": "Épicerie",
    "pistache": "Épicerie",
    "graine": "Épicerie",
    "sésame": "Épicerie",
    "cacahuète": "Épicerie",
    "pignon": "Épicerie",
    # Crème / sauces frigo
    "mascarpone": "Crèmerie",
    "ricotta": "Crèmerie",
    "crème fraîche": "Crèmerie",
    # Bébé
    "petit pot": "Bébé",
    "lait infantile": "Bébé",
}

# Mapping ingrédients -> (famille, sous-famille) pour regroupement intelligent
MAPPING_FAMILLES: dict[str, tuple[str, str]] = {
    # ── Volaille ──
    "poulet": ("Volaille", "Poulet"),
    "dinde": ("Volaille", "Dinde"),
    "canard": ("Volaille", "Canard"),
    "magret": ("Volaille", "Canard"),
    # ── Bœuf ──
    "steak": ("Bœuf", "Steak"),
    "bavette": ("Bœuf", "Steak"),
    "entrecôte": ("Bœuf", "Steak"),
    "faux-filet": ("Bœuf", "Steak"),
    "hach": ("Bœuf", "Haché"),
    "boeuf": ("Bœuf", "Autre"),
    "bœuf": ("Bœuf", "Autre"),
    # ── Porc ──
    "porc": ("Porc", "Autre"),
    "côte de porc": ("Porc", "Côte"),
    "rôti de porc": ("Porc", "Rôti"),
    # ── Agneau & Veau ──
    "agneau": ("Agneau & Veau", "Agneau"),
    "gigot": ("Agneau & Veau", "Agneau"),
    "souris d'agneau": ("Agneau & Veau", "Agneau"),
    "veau": ("Agneau & Veau", "Veau"),
    "blanquette": ("Agneau & Veau", "Veau"),
    # ── Viande (générique) ──
    "viande": ("Viande", "Autre"),
    "escalope": ("Viande", "Escalope"),
    # ── Poisson ──
    "saumon": ("Poisson", "Saumon"),
    "cabillaud": ("Poisson", "Cabillaud"),
    "colin": ("Poisson", "Cabillaud"),
    "lieu": ("Poisson", "Cabillaud"),
    "thon": ("Poisson", "Thon"),
    "truite": ("Poisson", "Truite"),
    "sardine": ("Poisson", "Autre"),
    "poisson": ("Poisson", "Autre"),
    # ── Fruits de mer ──
    "crevette": ("Fruits de mer", "Crevettes"),
    "moule": ("Fruits de mer", "Moules"),
    # ── Charcuterie ──
    "jambon": ("Charcuterie", "Jambon"),
    "lardon": ("Charcuterie", "Lardons"),
    "bacon": ("Charcuterie", "Lardons"),
    "saucisse": ("Charcuterie", "Saucisses"),
    "merguez": ("Charcuterie", "Saucisses"),
    "chorizo": ("Charcuterie", "Saucisses"),
    "saucisson": ("Charcuterie", "Saucisson"),
    # ── Fromage ──
    "gruyère": ("Fromage", "Râpé"),
    "emmental": ("Fromage", "Râpé"),
    "râpé": ("Fromage", "Râpé"),
    "parmesan": ("Fromage", "Râpé"),
    "mozzarella": ("Fromage", "Frais"),
    "chèvre": ("Fromage", "Frais"),
    "ricotta": ("Fromage", "Frais"),
    "mascarpone": ("Fromage", "Frais"),
    "comté": ("Fromage", "Affiné"),
    "camembert": ("Fromage", "Affiné"),
    "roquefort": ("Fromage", "Affiné"),
    "fromage": ("Fromage", "Autre"),
    # ── Produits laitiers ──
    "lait infantile": ("Bébé", "Lait"),
    "lait d'avoine": ("Bio & Végétal", "Lait végétal"),
    "lait de soja": ("Bio & Végétal", "Lait végétal"),
    "lait": ("Produits laitiers", "Lait"),
    "beurre": ("Produits laitiers", "Beurre"),
    "crème fraîche": ("Produits laitiers", "Crème"),
    "crème": ("Produits laitiers", "Crème"),
    "yaourt": ("Produits laitiers", "Yaourt"),
    "petit-suisse": ("Produits laitiers", "Yaourt"),
    "fromage blanc": ("Produits laitiers", "Yaourt"),
    "oeuf": ("Produits laitiers", "Œufs"),
    "œuf": ("Produits laitiers", "Œufs"),
    "compote": ("Produits laitiers", "Compote"),
    # ── Légumes ──
    "tomate": ("Légumes", "Légumes-fruits"),
    "courgette": ("Légumes", "Légumes-fruits"),
    "poivron": ("Légumes", "Légumes-fruits"),
    "aubergine": ("Légumes", "Légumes-fruits"),
    "concombre": ("Légumes", "Légumes-fruits"),
    "avocat": ("Légumes", "Légumes-fruits"),
    "carotte": ("Légumes", "Racines"),
    "pomme de terre": ("Légumes", "Racines"),
    "patate douce": ("Légumes", "Racines"),
    "navet": ("Légumes", "Racines"),
    "radis": ("Légumes", "Racines"),
    "betterave": ("Légumes", "Racines"),
    "panais": ("Légumes", "Racines"),
    "salade": ("Légumes", "Feuilles"),
    "épinard": ("Légumes", "Feuilles"),
    "endive": ("Légumes", "Feuilles"),
    "mâche": ("Légumes", "Feuilles"),
    "laitue": ("Légumes", "Feuilles"),
    "chou": ("Légumes", "Feuilles"),
    "oignon": ("Légumes", "Bulbes"),
    "ail": ("Légumes", "Bulbes"),
    "échalote": ("Légumes", "Bulbes"),
    "poireau": ("Légumes", "Bulbes"),
    "fenouil": ("Légumes", "Bulbes"),
    "céleri": ("Légumes", "Bulbes"),
    "brocoli": ("Légumes", "Fleurs"),
    "chou-fleur": ("Légumes", "Fleurs"),
    "artichaut": ("Légumes", "Fleurs"),
    "asperge": ("Légumes", "Fleurs"),
    "courge": ("Légumes", "Courges"),
    "potiron": ("Légumes", "Courges"),
    "butternut": ("Légumes", "Courges"),
    "potimarron": ("Légumes", "Courges"),
    "champignon": ("Légumes", "Champignons"),
    "haricot vert": ("Légumes", "Petits légumes"),
    "petit pois": ("Légumes", "Petits légumes"),
    "légume": ("Légumes", "Autre"),
    # ── Fruits ──
    "pomme": ("Fruits", "Courants"),
    "banane": ("Fruits", "Courants"),
    "poire": ("Fruits", "Courants"),
    "raisin": ("Fruits", "Courants"),
    "kiwi": ("Fruits", "Courants"),
    "orange": ("Fruits", "Agrumes"),
    "citron": ("Fruits", "Agrumes"),
    "clémentine": ("Fruits", "Agrumes"),
    "pamplemousse": ("Fruits", "Agrumes"),
    "fraise": ("Fruits", "Rouges"),
    "framboise": ("Fruits", "Rouges"),
    "cerise": ("Fruits", "Rouges"),
    "myrtille": ("Fruits", "Rouges"),
    "mûre": ("Fruits", "Rouges"),
    "groseille": ("Fruits", "Rouges"),
    "cassis": ("Fruits", "Rouges"),
    "mangue": ("Fruits", "Exotiques"),
    "ananas": ("Fruits", "Exotiques"),
    "melon": ("Fruits", "Exotiques"),
    "pastèque": ("Fruits", "Exotiques"),
    "nectarine": ("Fruits", "Exotiques"),
    "pêche": ("Fruits", "Exotiques"),
    "abricot": ("Fruits", "Exotiques"),
    "figue": ("Fruits", "Exotiques"),
    "fruit": ("Fruits", "Autre"),
    # ── Herbes fraîches ──
    "persil": ("Herbes fraîches", "Herbes"),
    "coriandre": ("Herbes fraîches", "Herbes"),
    "basilic": ("Herbes fraîches", "Herbes"),
    "menthe": ("Herbes fraîches", "Herbes"),
    "ciboulette": ("Herbes fraîches", "Herbes"),
    "thym": ("Herbes fraîches", "Aromates"),
    "romarin": ("Herbes fraîches", "Aromates"),
    "laurier": ("Herbes fraîches", "Aromates"),
    "herbe": ("Herbes fraîches", "Autre"),
    # ── Féculents & Céréales ──
    "pâtes": ("Féculents & Céréales", "Pâtes"),
    "nouille": ("Féculents & Céréales", "Pâtes"),
    "riz": ("Féculents & Céréales", "Riz"),
    "semoule": ("Féculents & Céréales", "Semoules"),
    "couscous": ("Féculents & Céréales", "Semoules"),
    "boulgour": ("Féculents & Céréales", "Semoules"),
    "quinoa": ("Féculents & Céréales", "Autres"),
    "farine": ("Féculents & Céréales", "Farine"),
    "maïzena": ("Féculents & Céréales", "Farine"),
    # ── Légumineuses ──
    "lentille": ("Légumineuses", "Lentilles"),
    "pois chiche": ("Légumineuses", "Pois chiches"),
    "haricot": ("Légumineuses", "Haricots"),
    # ── Épicerie sèche ──
    "sucre": ("Épicerie sèche", "Sucre"),
    "levure": ("Épicerie sèche", "Sucre"),
    "huile": ("Épicerie sèche", "Huile"),
    "sel": ("Épicerie sèche", "Sel & Poivre"),
    "poivre": ("Épicerie sèche", "Sel & Poivre"),
    "épice": ("Épicerie sèche", "Épices"),
    "cumin": ("Épicerie sèche", "Épices"),
    "paprika": ("Épicerie sèche", "Épices"),
    "curry": ("Épicerie sèche", "Épices"),
    "curcuma": ("Épicerie sèche", "Épices"),
    "cannelle": ("Épicerie sèche", "Épices"),
    "gingembre": ("Épicerie sèche", "Épices"),
    "noix de muscade": ("Épicerie sèche", "Épices"),
    "piment": ("Épicerie sèche", "Épices"),
    "origan": ("Épicerie sèche", "Épices"),
    "chapelure": ("Épicerie sèche", "Panure"),
    "bouillon": ("Épicerie sèche", "Bouillon"),
    # ── Condiments & Sauces ──
    "vinaigre": ("Condiments & Sauces", "Vinaigre"),
    "moutarde": ("Condiments & Sauces", "Moutarde"),
    "sauce soja": ("Condiments & Sauces", "Sauces"),
    "ketchup": ("Condiments & Sauces", "Sauces"),
    "mayonnaise": ("Condiments & Sauces", "Sauces"),
    "sauce": ("Condiments & Sauces", "Sauces"),
    "pesto": ("Condiments & Sauces", "Sauces"),
    "concentré": ("Condiments & Sauces", "Concentrés"),
    "coulis": ("Condiments & Sauces", "Concentrés"),
    # ── Conserves ──
    "conserve": ("Conserves", "Autre"),
    "tomate pelée": ("Conserves", "Tomates"),
    "pulpe": ("Conserves", "Tomates"),
    "maïs": ("Conserves", "Légumes"),
    "olive": ("Conserves", "Condiments"),
    "câpre": ("Conserves", "Condiments"),
    "cornichon": ("Conserves", "Condiments"),
    # ── Noix & Graines ──
    "amande": ("Noix & Graines", "Noix"),
    "noisette": ("Noix & Graines", "Noix"),
    "noix": ("Noix & Graines", "Noix"),
    "pistache": ("Noix & Graines", "Noix"),
    "cacahuète": ("Noix & Graines", "Noix"),
    "pignon": ("Noix & Graines", "Graines"),
    "graine": ("Noix & Graines", "Graines"),
    "sésame": ("Noix & Graines", "Graines"),
    # ── Petit-déjeuner ──
    "céréale": ("Petit-déjeuner", "Céréales"),
    "confiture": ("Petit-déjeuner", "Tartines"),
    "miel": ("Petit-déjeuner", "Tartines"),
    "chocolat": ("Petit-déjeuner", "Chocolat"),
    "cacao": ("Petit-déjeuner", "Chocolat"),
    "nutella": ("Petit-déjeuner", "Tartines"),
    # ── Boulangerie ──
    "pain": ("Boulangerie", "Pain"),
    "baguette": ("Boulangerie", "Pain"),
    "brioche": ("Boulangerie", "Viennoiserie"),
    # ── Boissons ──
    "jus": ("Boissons", "Jus"),
    "eau": ("Boissons", "Eau"),
    "sirop": ("Boissons", "Sirop"),
    # ── Bio & Végétal ──
    "tofu": ("Bio & Végétal", "Protéines"),
    "tempeh": ("Bio & Végétal", "Protéines"),
    # ── Surgelés ──
    "surgelé": ("Surgelés", "Autre"),
    "glace": ("Surgelés", "Desserts"),
    # ── Bébé ──
    "petit pot": ("Bébé", "Petits pots"),
}

# Priorités par rayon (1 = haute, 3 = basse)
PRIORITES: dict[str, int] = {
    "Boucherie": 1,  # Priorité haute (périme vite)
    "Charcuterie": 1,
    "Poissonnerie": 1,
    "Crèmerie": 1,
    "Fromage": 1,
    "Fruits & Légumes": 2,
    "Boulangerie": 2,
    "Surgelés": 2,
    "Bébé": 2,
    "Bio": 2,
    "Épicerie": 3,  # Priorité basse (se conserve)
    "Boissons": 3,
    "Autre": 3,
}

__all__ = ["MAPPING_FAMILLES", "MAPPING_RAYONS", "PRIORITES"]
