"""
Constantes pour le package courses.

Mappings rayons et priorités pour la catégorisation des articles.
"""

# Mapping ingrédients -> rayons magasin (complet)
MAPPING_RAYONS: dict[str, str] = {
    # Fruits & Légumes
    "tomate": "Fruits & Légumes",
    "carotte": "Fruits & Légumes",
    "oignon": "Fruits & Légumes",
    "ail": "Fruits & Légumes",
    "pomme de terre": "Fruits & Légumes",
    "courgette": "Fruits & Légumes",
    "poivron": "Fruits & Légumes",
    "salade": "Fruits & Légumes",
    "concombre": "Fruits & Légumes",
    "aubergine": "Fruits & Légumes",
    "champignon": "Fruits & Légumes",
    "poireau": "Fruits & Légumes",
    "chou": "Fruits & Légumes",
    "épinard": "Fruits & Légumes",
    "haricot vert": "Fruits & Légumes",
    "brocoli": "Fruits & Légumes",
    "navet": "Fruits & Légumes",
    "radis": "Fruits & Légumes",
    "fenouil": "Fruits & Légumes",
    "céleri": "Fruits & Légumes",
    "endive": "Fruits & Légumes",
    "betterave": "Fruits & Légumes",
    "artichaut": "Fruits & Légumes",
    "courge": "Fruits & Légumes",
    "potiron": "Fruits & Légumes",
    "butternut": "Fruits & Légumes",
    "patate douce": "Fruits & Légumes",
    "pomme": "Fruits & Légumes",
    "banane": "Fruits & Légumes",
    "orange": "Fruits & Légumes",
    "citron": "Fruits & Légumes",
    "fraise": "Fruits & Légumes",
    "avocat": "Fruits & Légumes",
    "mangue": "Fruits & Légumes",
    "abricot": "Fruits & Légumes",
    "pêche": "Fruits & Légumes",
    "poire": "Fruits & Légumes",
    "raisin": "Fruits & Légumes",
    "kiwi": "Fruits & Légumes",
    "ananas": "Fruits & Légumes",
    "melon": "Fruits & Légumes",
    "cerise": "Fruits & Légumes",
    "fruit": "Fruits & Légumes",
    "légume": "Fruits & Légumes",
    # Herbes fraîches
    "persil": "Fruits & Légumes",
    "coriandre": "Fruits & Légumes",
    "basilic": "Fruits & Légumes",
    "menthe": "Fruits & Légumes",
    "herbe": "Fruits & Légumes",
    "ciboulette": "Fruits & Légumes",
    "thym": "Fruits & Légumes",
    "romarin": "Fruits & Légumes",
    "laurier": "Fruits & Légumes",
    # Boulangerie
    "pain": "Boulangerie",
    "baguette": "Boulangerie",
    "brioche": "Boulangerie",
    # Boucherie
    "poulet": "Boucherie",
    "boeuf": "Boucherie",
    "porc": "Boucherie",
    "veau": "Boucherie",
    "agneau": "Boucherie",
    "steak": "Boucherie",
    "escalope": "Boucherie",
    "dinde": "Boucherie",
    "hach": "Boucherie",
    "viande": "Boucherie",
    # Charcuterie
    "jambon": "Charcuterie",
    "lardon": "Charcuterie",
    "saucisse": "Charcuterie",
    "saucisson": "Charcuterie",
    "merguez": "Charcuterie",
    "chorizo": "Charcuterie",
    "bacon": "Charcuterie",
    # Poissonnerie
    "saumon": "Poissonnerie",
    "cabillaud": "Poissonnerie",
    "crevette": "Poissonnerie",
    "thon": "Poissonnerie",
    "moule": "Poissonnerie",
    "poisson": "Poissonnerie",
    "colin": "Poissonnerie",
    "truite": "Poissonnerie",
    "lieu": "Poissonnerie",
    "sardine": "Poissonnerie",
    # Crèmerie / Frais
    "lait": "Crèmerie",
    "beurre": "Crèmerie",
    "crème": "Crèmerie",
    "yaourt": "Crèmerie",
    "oeuf": "Crèmerie",
    "œuf": "Crèmerie",
    "compote": "Crèmerie",
    "petit-suisse": "Crèmerie",
    # Fromage
    "fromage": "Fromage",
    "gruyère": "Fromage",
    "emmental": "Fromage",
    "parmesan": "Fromage",
    "mozzarella": "Fromage",
    "comté": "Fromage",
    "chèvre": "Fromage",
    "camembert": "Fromage",
    "roquefort": "Fromage",
    "râpé": "Fromage",
    # Épicerie salée
    "pâtes": "Épicerie",
    "riz": "Épicerie",
    "semoule": "Épicerie",
    "quinoa": "Épicerie",
    "boulgour": "Épicerie",
    "couscous": "Épicerie",
    "nouille": "Épicerie",
    "huile": "Épicerie",
    "sel": "Épicerie",
    "poivre": "Épicerie",
    "farine": "Épicerie",
    "sucre": "Épicerie",
    "levure": "Épicerie",
    "maïzena": "Épicerie",
    "bouillon": "Épicerie",
    "épice": "Épicerie",
    "cumin": "Épicerie",
    "paprika": "Épicerie",
    "curry": "Épicerie",
    "curcuma": "Épicerie",
    "cannelle": "Épicerie",
    "gingembre": "Épicerie",
    "noix de muscade": "Épicerie",
    "piment": "Épicerie",
    "origan": "Épicerie",
    "chapelure": "Épicerie",
    # Condiments
    "vinaigre": "Épicerie",
    "moutarde": "Épicerie",
    "sauce soja": "Épicerie",
    "ketchup": "Épicerie",
    "mayonnaise": "Épicerie",
    "sauce": "Épicerie",
    "pesto": "Épicerie",
    "concentré": "Épicerie",
    "coulis": "Épicerie",
    # Conserves
    "conserve": "Épicerie",
    "tomate pelée": "Épicerie",
    "haricot": "Épicerie",
    "pois chiche": "Épicerie",
    "lentille": "Épicerie",
    "maïs": "Épicerie",
    "olive": "Épicerie",
    "câpre": "Épicerie",
    "cornichon": "Épicerie",
    "pulpe": "Épicerie",
    # Petits-déjeuner
    "céréale": "Épicerie",
    "confiture": "Épicerie",
    "miel": "Épicerie",
    "chocolat": "Épicerie",
    "cacao": "Épicerie",
    "nutella": "Épicerie",
    # Boissons
    "jus": "Boissons",
    "eau": "Boissons",
    "sirop": "Boissons",
    # Bio / Végétal
    "tofu": "Bio",
    "lait d'avoine": "Bio",
    "lait de soja": "Bio",
    "tempeh": "Bio",
    # Surgelés
    "surgelé": "Surgelés",
    "glace": "Surgelés",
    # Noix et graines
    "amande": "Épicerie",
    "noisette": "Épicerie",
    "noix": "Épicerie",
    "pistache": "Épicerie",
    "graine": "Épicerie",
    "sésame": "Épicerie",
    "cacahuète": "Épicerie",
    "pignon": "Épicerie",
    # Crème / sauces frigo
    "mascarpone": "Crèmerie",
    "ricotta": "Crèmerie",
    "crème fraîche": "Crèmerie",
    # Bébé
    "petit pot": "Bébé",
    "lait infantile": "Bébé",
}

# Priorités par rayon (1 = haute, 3 = basse)
PRIORITES: dict[str, int] = {
    "Boucherie": 1,  # Priorité haute (périme vite)
    "Charcuterie": 1,
    "Poissonnerie": 1,
    "Crèmerie": 1,
    "Fromage": 1,
    "Fruits & Légumes": 2,
    "Boulangerie": 2,
    "Surgelés": 2,
    "Bébé": 2,
    "Bio": 2,
    "Épicerie": 3,  # Priorité basse (se conserve)
    "Boissons": 3,
    "Autre": 3,
}

__all__ = ["MAPPING_RAYONS", "PRIORITES"]
